### ISSUE TITLE
Click tracking in SparkPost?

### ISSUE THREAD

**Issue by herbdool** [proexchange/com.pesc.sparkpost#16]
I'm not sure if I'm missing something in the configuration of this extension. I see in SparkPost zero clicks so I'm assuming that this is a feature that hasn't been implemented and that we can only track them in Civi (if click tracking is enabled per mailing).

This isn't a high priority given the alternative in Civi, but would like it cleared up if this would be a future feature or not. Thanks!

**Comment by mark-rodgers** [comment]
I would not recommend editing the code since the custom code will get overwritten if you update the extension in the future, but if this is something you must have then you can add this one line in sparkpost.php on line 189, right below the campaign_id line.

'options' => array('open_tracking' => false, 'click_tracking' => true),

![image](https://cloud.githubusercontent.com/assets/2798202/14477660/2b3ccc24-00c4-11e6-83b5-9e438ec223b0.png)

The reason we we don't release the code with this enabled by default is because we don't want the tracking enabled by default. Using both tracking systems will cause 2 redirects since both SparkPost and CiviCRM will be tracking the clicks. This sometimes caused issues back with Mandrill and CiviCRM, so we would like to avoid that issue. If we add a configuration page in CiviCRM in a later release this will be something we can easily add a setting to toggle on or off from the UI, depending on the need of this feature.

**Comment by herbdool** [comment]
I agree this is a later enhancement (we don't need it now unless the client really wants to see it there). I would figure the toggle could also disable the civicrm click tracking or something like that.
